---
divide into train and test set
---

set working directory

```{r}
setwd("/scratchb/cclab/cope01/projects/")
```

Then start
```{r}
#load library
#install.packages("neuralnet")
#install.packages("nnet")
library(neuralnet)
library(nnet)

#load data
load("nanoStringIC_DF.RData")
nanoStringIC_DF <- na.omit(nanoStringIC_DF)
#nanoStringIC_DF$iClust<-paste0("x",nanoStringIC_DF$iClust)
#nanoStringIC_DF$iClust <- as.numeric(nanoStringIC_DF$iClust)
#Prepare data
df <- cbind(nanoStringIC_DF[, 2:213], class.ind(nanoStringIC_DF$iClust), nanoStringIC_DF$iClust)
names(df) <- c(names(nanoStringIC_DF[2:213]), "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "iClust")

##cross validation
pr.nn.list <- list()
accuracy.list <- list()
predicted <- matrix(0, nrow = round(0.8*nrow(nanoStringIC_DF)), ncol = 10)
```

Scale data and then separate into training set, test set 
```{r}
scale <- function(x){(x-min(x))/(max(x)-min(x))}
df[, 1:212] <- as.data.frame((lapply(df[, 1:212], scale)))
index <- sample(1:nrow(nanoStringIC_DF),round(0.8*nrow(nanoStringIC_DF)))
testNN <- df[-index,] 
trainNN <- df[index,]
```


Work on the training set - tweak until happy
```{r}
for (i in 1:nrow(trainNN)) {
  traintrainNN <- trainNN[-i,]
  genes <- names(df[1:212])
  class <- names(df[213:222])
  formula <- as.formula(paste(paste(class, collapse = "+"), "~", paste(genes, collapse = " + ")))

NN = neuralnet(formula, traintrainNN, hidden = c(80, 30), act.fct = "logistic", linear.output = F, lifesign = "minimal")

pr.nn.list[[i]] <- compute(NN,trainNN[i,1:212])
predicted[i,] <- pr.nn.list[[i]]$net.result

print(i)
}

predicted <- as.data.frame(predicted)

predicted.table <- table(factor(apply(predicted, 1, which.max), levels=1:10),trainNN$iClust) 
predicted.table
sum(diag(predicted.table))/sum(predicted.table)
```




When we're happy with training set, use the classifier on the test set

```{r}
for (j in 1:nrow(testNN)) {
pr.nn.list[[j]] <- compute(NN,testNN[1:212])
predicted[j,] <- pr.nn.list[[j]]$net.result
print(j)
}

predicted <- as.data.frame(predicted)

predicted.table <- table(factor(apply(predicted, 1, which.max), levels=1:10),testNN[, 223]) 
#predicted.table
sum(diag(predicted.table))/sum(predicted.table)

```

